server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: USER-SERVICE

  config:
    import: optional:configserver:http://localhost:8085
#  profiles:
#    active: dev

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka


# Resilience4j Configuration
resilience4j.circuitbreaker:
  instances:
    # 'ratingHotelBreaker' wo naam hai jo aap @CircuitBreaker annotation mein use karenge
    ratingHotelBreaker:
      registerHealthIndicator: true
      slidingWindowSize: 10              # Last 10 calls ko check karega
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5            # Kam se kam 5 calls ke baad decision lega
      waitDurationInOpenState: 10s       # 10 second tak circuit OPEN rahega (failure pe)
      failureRateThreshold: 50           # Agar 50% calls fail hui toh circuit OPEN

resilience4j:
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 3s



# Actuator settings taaki aap health check dekh sakein
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always

